//
//  GoldenVectorsTests.swift
//  KDNACoreTests
//
//  Cross-language parity test: reads test-vectors/golden-v1.json
//  (generated by the JS-side test-vectors/generate.js against
//  @aikdna/kdna-core@0.15.0) and verifies that the Swift CryptoKit
//  implementation produces the same AES-256-GCM ciphertext + scrypt KDF
//  for the same inputs.
//
//  The Swift encrypt path is currently NOT implemented (see ADR-005
//  §5 — License verifySignature already throws unsupportedProfile).
//  When the Swift side lands kdna-password-protected-v1-scrypt (B2),
//  this test should pass.
//
//  Status: placeholder. The test loads the fixture and asserts structural
//  fields (profile, kdf, scrypt_params); the encrypt-side comparison
//  is gated on Swift B2 implementation landing.

import XCTest
import CryptoKit
@testable import KDNACore

final class GoldenVectorsTests: XCTestCase {

    private struct GoldenVectorFile: Decodable {
        let version: Int
        let kdna_core_version: String
        struct V: Decodable {
            struct Scrypt: Decodable {
                let profile: String
                let alg: String
                let kdf: String
                let key_wrapping: String
                let scrypt_params: [String: AnyDecodable]
                let key_slots: [AnyDecodable]
                let iv: String
                let tag: String
                let ciphertext: String
                let plaintext: String
                let wrong_password_fails: Bool
            }
            struct Licensed: Decodable {
                let profile: String
                let alg: String
                let kdf: String
                let key_wrapping: String
                let wrapped_key: String
                let iv: String
                let tag: String
                let ciphertext: String
                let plaintext: String
            }
            let scrypt_password_v1: Scrypt
            let licensed_entry_v1: Licensed
        }
        let vectors: V
    }

    // Minimal AnyDecodable to keep JSON parsing resilient
    private struct AnyDecodable: Decodable {
        let value: Any
        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let v = try? c.decode(String.self) { value = v; return }
            if let v = try? c.decode(Int.self) { value = v; return }
            if let v = try? c.decode(Double.self) { value = v; return }
            if let v = try? c.decode(Bool.self) { value = v; return }
            if let v = try? c.decode([String: AnyDecodable].self) { value = v; return }
            if let v = try? c.decode([AnyDecodable].self) { value = v; return }
            value = NSNull()
        }
    }

    private func loadVectors() throws -> GoldenVectorFile {
        let url = Bundle(for: GoldenVectorsTests.self)
            .url(forResource: "golden-v1", withExtension: "json", subdirectory: "Fixtures")
            ?? Bundle(for: GoldenVectorsTests.self)
            .url(forResource: "golden-v1", withExtension: "json")
        XCTAssertNotNil(url, "test-vectors/golden-v1.json must be added to KDNACoreTests Fixtures")
        let data = try Data(contentsOf: url!)
        return try JSONDecoder().decode(GoldenVectorFile.self, from: data)
    }

    func testGoldenVectorFileStructure() throws {
        let v = try loadVectors()
        XCTAssertEqual(v.version, 1)
        XCTAssertEqual(v.kdna_core_version, "0.15.0")
        XCTAssertEqual(v.vectors.scrypt_password_v1.profile, "kdna-password-protected-v1-scrypt")
        XCTAssertEqual(v.vectors.scrypt_password_v1.kdf, "scrypt-sha256")
        XCTAssertEqual(v.vectors.scrypt_password_v1.alg, "AES-256-GCM")
        XCTAssertEqual(v.vectors.scrypt_password_v1.key_wrapping, "AES-256-KW")
        XCTAssertEqual(v.vectors.scrypt_password_v1.scrypt_params["N"]?.value as? Int, 32768)
        XCTAssertEqual(v.vectors.scrypt_password_v1.scrypt_params["r"]?.value as? Int, 8)
        XCTAssertEqual(v.vectors.scrypt_password_v1.scrypt_params["p"]?.value as? Int, 1)
        XCTAssertTrue(v.vectors.scrypt_password_v1.wrong_password_fails)
    }

    // ── When Swift B2 lands: ──────────────────────────────────────
    //
    // func testScryptRoundTripParity() throws {
    //     let v = try loadVectors().vectors.scrypt_password_v1
    //     let password = "kdna-test-password-2026"
    //     let plaintext = v.plaintext
    //
    //     let ciphertext = try KDNACoreSwift.encryptProtectedEntryScrypt(
    //         plaintext: Data(plaintext.utf8),
    //         entryName: "payload.kdnab",
    //         manifest: KDNAManifest(name: "kdna:vector:test", asset_id: "kdna:vector:test", version: "0.1.0"),
    //         password: password
    //     )
    //
    //     // Same IV and plaintext → same ciphertext (deterministic given IV)
    //     // The JS side generates a random IV; we can only compare via round-trip
    //     let decrypted = try KDNACoreSwift.decryptProtectedEntryScrypt(
    //         ciphertext,
    //         entryName: "payload.kdnab",
    //         manifest: KDNAManifest(name: "kdna:vector:test", asset_id: "kdna:vector:test", version: "0.1.0"),
    //         password: password
    //     )
    //     XCTAssertEqual(String(data: decrypted, encoding: .utf8), plaintext)
    // }
    //
    // ── When Swift B6 lands: ──────────────────────────────────────
    //
    // func testLicenseVerifySignatureParity() throws {
    //     // Fixture: license activation record signed by JS-side test key
    //     // Swift must reject without throwing (when B6 is implemented) and
    //     // accept with valid Ed25519 signature.
    // }
}
